# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Build settings

locale: en-US
title: Jaehyuk
email: jhyuk.lee@outlook.com
url: "http://ruach.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

disqus:
  shortname: "jaehyuk"
github_username:  ruach

mathjax:
  enable: true

search_full_content: true


# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true


# Site Author
author:
  name: Jaehyuk Lee
  picture: /images/jaehyuk.jpeg
  email: jhyuk.lee@outlook.com
  links:
    - title: GitHub
      url: https://github.com/ruach
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/ruach
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/jaehyuk-lee-29b33b121/
    icon: fab fa-linkedin
  - title: StackOverflow
    url: https://stackoverflow.com/users/4460514/jaehyuk-lee?tab=profile
    icon: fab fa-stack-overflow
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

